<TOPOLOGY>
    <COMPONENT>
        <ONOScell>
            <host>localhost</host>  # ONOS "bench" machine
            <user>sdn</user>
            <password>rocks</password>
            <type>OnosClusterDriver</type>
            <connect_order>1</connect_order>
            <COMPONENTS>
                <cluster_name></cluster_name>  # Used as a prefix for cluster components. Defaults to 'ONOS'
                <diff_clihost></diff_clihost> # if it has different host other than localhost for CLI. True or empty. OC# will be used if True.
                <karaf_username>ubuntu</karaf_username>
                <karaf_password>ubuntu</karaf_password>
                <web_user></web_user>
                <web_pass></web_pass>
                <rest_port></rest_port>
                <prompt></prompt>  # TODO: we technically need a few of these, one per component
                <onos_home></onos_home>  # defines where onos home is
                <nodes> 3 </nodes>  # number of nodes in the cluster
            </COMPONENTS>
        </ONOScell>

        <OFDPASwitchLeaf201>
            <host>10.192.21.22</host>
            <user>root</user>
            <password></password>
            <type>OFDPASwitchDriver</type>
            <connect_order>2</connect_order>
            <COMPONENTS>
                <shortName>s201</shortName>
                <dpid>0x201</dpid>
                <confDir>/etc/ofdpa/</confDir>
                <link1>
                    <node2>OFDPASwitchLeaf226</node2>
                    <port2>29</port2>
                    <port1>49</port1>
                </link1>
                <link2>
                    <node2>OFDPASwitchLeaf226</node2>
                    <port2>30</port2>
                    <port1>50</port1>
                </link2>
                <link3>
                    <node2>OFDPASwitchLeaf225</node2>
                    <port2>29</port2>
                    <port1>51</port1>
                </link3>
                <link4>
                    <node2>OFDPASwitchLeaf225</node2>
                    <port2>30</port2>
                    <port1>52</port1>
                </link4>
                <link5>
                    <node2>OFDPASwitchLeaf202</node2>
                    <port2>20</port2>
                    <port1>20</port1>
                </link5>
            </COMPONENTS>
        </OFDPASwitchLeaf201>

        <OFDPASwitchLeaf202>
            <host>10.192.21.23</host>
            <user>root</user>
            <password></password>
            <type>OFDPASwitchDriver</type>
            <connect_order>3</connect_order>
            <COMPONENTS>
                <shortName>s202</shortName>
                <dpid>0x202</dpid>
                <confDir>/etc/ofdpa/</confDir>
                <link1>
                    <node2>OFDPASwitchLeaf225</node2>
                    <port2>26</port2>
                    <port1>49</port1>
                </link1>
                <link2>
                    <node2>OFDPASwitchLeaf226</node2>
                    <port2>28</port2>
                    <port1>50</port1>
                </link2>
                <link3>
                    <node2>OFDPASwitchLeaf226</node2>
                    <port2>27</port2>
                    <port1>51</port1>
                </link3>
                <link4>
                    <node2>OFDPASwitchLeaf201</node2>
                    <port2>20</port2>
                    <port1>20</port1>
                </link4>
            </COMPONENTS>
        </OFDPASwitchLeaf202>

        <OFDPASwitchLeaf203>
            <host>10.192.21.24</host>
            <user>root</user>
            <password></password>
            <type>OFDPASwitchDriver</type>
            <connect_order>4</connect_order>
            <COMPONENTS>
                <shortName>s203</shortName>
                <dpid>0x203</dpid>
                <confDir>/etc/ofdpa/</confDir>
                <link1>
                    <node2>OFDPASwitchLeaf225</node2>
                    <port2>23</port2>
                    <port1>49</port1>
                </link1>
                <link2>
                    <node2>OFDPASwitchLeaf226</node2>
                    <port2>25</port2>
                    <port1>50</port1>
                </link2>
                <link3>
                    <node2>OFDPASwitchLeaf226</node2>
                    <port2>26</port2>
                    <port1>51</port1>
                </link3>
                <link4>
                    <node2>OFDPASwitchLeaf225</node2>
                    <port2>24</port2>
                    <port1>52</port1>
                </link4>
                <link5>
                    <node2>OFDPASwitchLeaf204</node2>
                    <port2>20</port2>
                    <port1>20</port1>
                </link5>
            </COMPONENTS>
        </OFDPASwitchLeaf203>

        <OFDPASwitchLeaf204>
            <host>10.192.21.25</host>
            <user>root</user>
            <password></password>
            <type>OFDPASwitchDriver</type>
            <connect_order>5</connect_order>
            <COMPONENTS>
                <shortName>s204</shortName>
                <dpid>0x204</dpid>
                <confDir>/etc/ofdpa/</confDir>
                <link1>
                    <node2>OFDPASwitchLeaf226</node2>
                    <port2>32</port2>
                    <port1>50</port1>
                </link1>
                <link2>
                    <node2>OFDPASwitchLeaf225</node2>
                    <port2>31</port2>
                    <port1>51</port1>
                </link2>
                <link3>
                    <node2>OFDPASwitchLeaf225</node2>
                    <port2>32</port2>
                    <port1>52</port1>
                </link3>
                <link4>
                    <node2>OFDPASwitchLeaf203</node2>
                    <port2>20</port2>
                    <port1>20</port1>
                </link4>
            </COMPONENTS>
        </OFDPASwitchLeaf204>

        <OFDPASwitchLeaf205>
            <host>10.192.21.29</host>
            <user>root</user>
            <password></password>
            <type>OFDPASwitchDriver</type>
            <connect_order>6</connect_order>
            <COMPONENTS>
                <shortName>s205</shortName>
                <dpid>0x205</dpid>
                <confDir>/etc/ofdpa/</confDir>
                <link1>
                    <node2>OFDPASwitchLeaf227</node2>
                    <port2>25</port2>
                    <port1>49</port1>
                </link1>
                <link2>
                    <node2>OFDPASwitchLeaf228</node2>
                    <port2>25</port2>
                    <port1>51</port1>
                </link2>
            </COMPONENTS>
        </OFDPASwitchLeaf205>

        <OFDPASwitchLeaf206>
            <host>10.192.21.30</host>
            <user>root</user>
            <password></password>
            <type>OFDPASwitchDriver</type>
            <connect_order>7</connect_order>
            <COMPONENTS>
                <shortName>s206</shortName>
                <dpid>0x206</dpid>
                <confDir>/etc/ofdpa/</confDir>
                <link1>
                    <node2>OFDPASwitchLeaf227</node2>
                    <port2>27</port2>
                    <port1>49</port1>
                </link1>
                <link2>
                    <node2>OFDPASwitchLeaf228</node2>
                    <port2>27</port2>
                    <port1>51</port1>
                </link2>
            </COMPONENTS>
        </OFDPASwitchLeaf206>

        <OFDPASwitchLeaf225>
            <host>10.192.21.21</host>
            <user>root</user>
            <password></password>
            <type>OFDPASwitchDriver</type>
            <connect_order>8</connect_order>
            <COMPONENTS>
                <shortName>s225</shortName>
                <dpid>0x225</dpid>
                <confDir>/etc/ofdpa/</confDir>
                <link1>
                    <node2>OFDPASwitchLeaf227</node2>
                    <port2>16</port2>
                    <port1>16</port1>
                </link1>
                <link2>
                    <node2>OFDPASwitchLeaf203</node2>
                    <port2>49</port2>
                    <port1>23</port1>
                </link2>
                <link3>
                    <node2>OFDPASwitchLeaf203</node2>
                    <port2>52</port2>
                    <port1>24</port1>
                </link3>
                <link4>
                    <node2>OFDPASwitchLeaf202</node2>
                    <port2>49</port2>
                    <port1>26</port1>
                </link4>
                <link5>
                    <node2>OFDPASwitchLeaf201</node2>
                    <port2>51</port2>
                    <port1>29</port1>
                </link5>
                <link6>
                    <node2>OFDPASwitchLeaf201</node2>
                    <port2>52</port2>
                    <port1>30</port1>
                </link6>
                <link7>
                    <node2>OFDPASwitchLeaf204</node2>
                    <port2>51</port2>
                    <port1>31</port1>
                </link7>
                <link8>
                    <node2>OFDPASwitchLeaf204</node2>
                    <port2>52</port2>
                    <port1>32</port1>
                </link8>
            </COMPONENTS>
        </OFDPASwitchLeaf225>

        <OFDPASwitchLeaf226>
            <host>10.192.21.26</host>
            <user>root</user>
            <password></password>
            <type>OFDPASwitchDriver</type>
            <connect_order>9</connect_order>
            <COMPONENTS>
                <shortName>s226</shortName>
                <dpid>0x226</dpid>
                <confDir>/etc/ofdpa/</confDir>
                <link1>
                    <node2>OFDPASwitchLeaf228</node2>
                    <port2>16</port2>
                    <port1>16</port1>
                </link1>
                <link2>
                    <node2>OFDPASwitchLeaf203</node2>
                    <port2>50</port2>
                    <port1>25</port1>
                </link2>
                <link3>
                    <node2>OFDPASwitchLeaf203</node2>
                    <port2>51</port2>
                    <port1>26</port1>
                </link3>
                <link4>
                    <node2>OFDPASwitchLeaf202</node2>
                    <port2>51</port2>
                    <port1>27</port1>
                </link4>
                <link5>
                    <node2>OFDPASwitchLeaf202</node2>
                    <port2>50</port2>
                    <port1>28</port1>
                </link5>
                <link6>
                    <node2>OFDPASwitchLeaf201</node2>
                    <port2>49</port2>
                    <port1>29</port1>
                </link6>
                <link7>
                    <node2>OFDPASwitchLeaf201</node2>
                    <port2>50</port2>
                    <port1>30</port1>
                </link7>
                <link8>
                    <node2>OFDPASwitchLeaf204</node2>
                    <port2>50</port2>
                    <port1>32</port1>
                </link8>
            </COMPONENTS>
        </OFDPASwitchLeaf226>

        <OFDPASwitchLeaf227>
            <host>10.192.21.28</host>
            <user>root</user>
            <password></password>
            <type>OFDPASwitchDriver</type>
            <connect_order>10</connect_order>
            <COMPONENTS>
                <shortName>s227</shortName>
                <dpid>0x227</dpid>
                <confDir>/etc/ofdpa/</confDir>
                <link1>
                    <node2>OFDPASwitchLeaf225</node2>
                    <port2>16</port2>
                    <port1>16</port1>
                </link1>
                <link2>
                    <node2>OFDPASwitchLeaf205</node2>
                    <port2>49</port2>
                    <port1>25</port1>
                </link2>
                <link3>
                    <node2>OFDPASwitchLeaf206</node2>
                    <port2>49</port2>
                    <port1>27</port1>
                </link3>
            </COMPONENTS>
        </OFDPASwitchLeaf227>

        <OFDPASwitchLeaf228>
            <host>10.192.21.31</host>
            <user>root</user>
            <password></password>
            <type>OFDPASwitchDriver</type>
            <connect_order>11</connect_order>
            <COMPONENTS>
                <shortName>s228</shortName>
                <dpid>0x228</dpid>
                <confDir>/etc/ofdpa/</confDir>
                <link1>
                    <node2>OFDPASwitchLeaf226</node2>
                    <port2>16</port2>
                    <port1>16</port1>
                </link1>
                <link2>
                    <node2>OFDPASwitchLeaf205</node2>
                    <port2>51</port2>
                    <port1>25</port1>
                </link2>
                <link3>
                    <node2>OFDPASwitchLeaf206</node2>
                    <port2>51</port2>
                    <port1>27</port1>
                </link3>
            </COMPONENTS>
        </OFDPASwitchLeaf228>

        <Host4v4>
            <host>10.192.21.61</host>
            <user>vyatta</user>
            <password>vyatta</password>
            <type>HostDriver</type>
            <connect_order>13</connect_order>
            <COMPONENTS>
                <ip>10.0.202.7</ip>
                <ip6></ip6>
                <shortName>h4v4</shortName>
                <mac>0A:5E:0D:F3:EC:D4</mac>
                <ifaceName>bond0</ifaceName>
                <inband>True</inband>
                <username>ubuntu</username>
                <password>ubuntu</password>
            </COMPONENTS>
        </Host4v4>

        <Host5v4>
            <host>10.192.21.61</host>
            <user>vyatta</user>
            <password>vyatta</password>
            <type>HostDriver</type>
            <connect_order>14</connect_order>
            <COMPONENTS>
                <ip>10.0.202.8</ip>
                <ip6></ip6>
                <shortName>h5v4</shortName>
                <mac>12:1C:B7:5C:69:68</mac>
                <ifaceName>bond0</ifaceName>
                <inband>True</inband>
                <username>ubuntu</username>
                <password>ubuntu</password>
            </COMPONENTS>
        </Host5v4>

        <Host9v4>
            <host>10.192.21.61</host>
            <user>vyatta</user>
            <password>vyatta</password>
            <type>HostDriver</type>
            <connect_order>15</connect_order>
            <COMPONENTS>
                <ip>10.0.204.7</ip>
                <ip6></ip6>
                <shortName>h9v4</shortName>
                <mac>EA:DA:19:1E:CB:7D</mac>
                <ifaceName>bond0</ifaceName>
                <inband>True</inband>
                <username>ubuntu</username>
                <password>ubuntu</password>
            </COMPONENTS>
        </Host9v4>

        <Host10v4>
            <host>10.192.21.61</host>
            <user>vyatta</user>
            <password>vyatta</password>
            <type>HostDriver</type>
            <connect_order>16</connect_order>
            <COMPONENTS>
                <ip>10.0.204.8</ip>
                <ip6></ip6>
                <shortName>h10v4</shortName>
                <mac>A2:9B:16:E8:2A:52</mac>
                <ifaceName>bond0</ifaceName>
                <inband>True</inband>
                <username>ubuntu</username>
                <password>ubuntu</password>
            </COMPONENTS>
        </Host10v4>

        <NetworkBench>
            <host>localhost</host>
            <user>sdn</user>
            <password>rocks</password>
            <type>NetworkDriver</type>
            <connect_order>20</connect_order>
            <COMPONENTS>
            </COMPONENTS>
        </NetworkBench>
    </COMPONENT>
</TOPOLOGY>
